FROM python:3.9

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt
RUN pip install -r requirements.txt
COPY ./app /code/app
ENV PYTHONPATH "${PYTHONPATH}:/code/"
CMD ["python", "/code/app/main.py"]