version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq/
      - rabbit_log:/var/log/rabbitmq

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.fastApi
    environment:
      MONGO_INITDB_HOST: mongodb
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
    ports:
      - 8080:8080

  persistor:
    build:
      context: ./
      dockerfile: ./Dockerfile.persistor
    environment:
      MONGO_INITDB_HOST: mongodb
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
    volumes:
      - ./data/:/code/data
    restart: on-failure

volumes:
  mongodb_data: null
  rabbit_data: null
  rabbit_log: null
  persistor_data: null
