version: '3'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile.fastApi
    environment:
      MONGO_INITDB_HOST: mongodb
      MONGO_INITDB_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - 8080:8080

  

volumes: 
  mongodb_data_container:
